name: client
version: 0.0.1
dependencies:
  angular: ">=1.0.0 <2.0.0"
  browser: ">=0.10.0+2 <0.11.0"
  redstone_mapper_mongo: ">=0.1.1+1 <0.2.0"
  redstone_mapper: ">=0.1.9 <0.2.0"
  
dev_dependencies:
  unittest: '>=0.11.0+2 <0.12.0'
   
transformers:
  - redstone_mapper
  - angular:
      dart_sdk: "/dart-sdk/latest"

