name: server
dependencies:
  client:
    path: ../client/
  mongo_dart: ">=0.1.45 <0.2.0"
  redstone: ">=0.5.19 <0.6.0"
  connection_pool: ">=0.1.0+2 <0.2.0"  
  redstone_mapper_mongo: ">=0.1.1+1 <0.2.0"
  redstone_mapper: ">=0.1.9 <0.2.0"

  
